spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/yfwj?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lian8419
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: true
      write-date-keys-as-timestamps: true
    deserialization:
      read-date-timestamps-as-nanoseconds: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    use-root-path: true
  enable-native-support: true

server:
  port: 8089
