
server:
  port: 8086
spring:
  config:
    import: vault://secret/core.conf
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yfwj?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    password: lian8419
  application:
    name: keycloak-app
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      uri: ${spring.cloud.vault.scheme}://${spring.cloud.vault.host}:${spring.cloud.vault.port}
      token: hvs.ULiec1L3q6bJDx37yo5Pv1CA

      database:
        enabled: true







